### ISSUE TITLE
for Mobile resolution(<1000 width),footer is overlapping

### ISSUE THREAD

**Issue by hameedshk** [Kidzmile/Kidzmile#1]
Steps to reproduce:
1)After launching the application google chrome ,goto mobile view
2)change current resolution to any lesser than 1000 width.

**Result**:Content of footer overlaps with each other and for 700 width,the footer moves up next to header.

**Expectation** :Content of footer shouldnt overlaps with each other at any point of time  and for <700 width,the footer shouldnt move near to header.

![image](https://user-images.githubusercontent.com/16490176/46239469-a97ff680-c3b6-11e8-8a6e-d3738b1fad0d.png)

**Comment by harish1992** [comment]
fixed in latest update
