### ISSUE TITLE
Width and height of header and footer is comparatively more

### ISSUE THREAD

**Issue by hameedshk** [Kidzmile/Kidzmile#2]
Width and height of header and footer is comparatively more.

Attached are both snapshot of our local UI and https://angularspree.firebaseapp.com/  example UI.

Expected: There shouldnt  be any differnce between the two.
![image](https://user-images.githubusercontent.com/16490176/46239533-493d8480-c3b7-11e8-877d-e3fb8e2bca6e.png)
![image](https://user-images.githubusercontent.com/16490176/46239538-53f81980-c3b7-11e8-87ef-4a8bab0eab5a.png)
![image](https://user-images.githubusercontent.com/16490176/46239548-70945180-c3b7-11e8-991e-340120793f62.png)
![image](https://user-images.githubusercontent.com/16490176/46239553-7f7b0400-c3b7-11e8-9b97-b7a6f6ef3e33.png)

**Comment by harish1992** [comment]
fixed in latest commit
